#!/bin/bash

TOPIC_ARN="REPLACE THIS WITH AWS SNS TOPIC ARN" ## Make sure your instance has permissions to publish to this topic.
SLOW=${1:-5000}

process() {
    tmpfile=/tmp/msg.$$
    regex='^([^ ]*).*command: (.*) ([0-9]*)ms$'
    while read input
    do
        if [[ "$input" =~ $regex ]]
        then
            date=${BASH_REMATCH[1]}
            query=${BASH_REMATCH[2]}
            ms=${BASH_REMATCH[3]}
            if [ $ms -ge $SLOW ]
            then
                echo "SLOW QUERY ALERT - ${ms}ms" > $tmpfile
                echo >> $tmpfile
                echo "$date" >> $tmpfile
                echo '```' >> $tmpfile
                echo "$query" >> $tmpfile
                echo '```' >> $tmpfile
                aws sns publish --topic-arn $TOPIC_ARN --message file://$tmpfile --subject "PRODUCTION ALERT :: ${ms}ms query on $(hostname)"
                rm $tmpfile
            fi
        fi
    done
}

tail -F <LOCATION OF YOUR MONGODB LOG FILE> | grep 'ms$' | process
